# Menggunakan image dasar Nginx
FROM nginx:latest

# Menyalin konfigurasi Nginx ke dalam container
COPY default.conf /etc/nginx/conf.d/default.conf

# Menyalin file aplikasi web ke direktori html Nginx

# Expose port 80 agar bisa diakses dari luar container
EXPOSE 80
